// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.extensions.webcompat.disabled_shims.AdvertisingDotCom", true);
user_pref("app.normandy.user_id", "166592b9-d411-49a7-a988-0a756389d9cc");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1670389043);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1670389080);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{2a3e86a5-34ec-42d1-b8c0-5ad1f084a31d}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1670389040);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 132);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5e341ac2-3fad-4c20-8a4e-706a28deccc3}");
user_pref("browser.newtabpage.pinned", "[]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1670389041);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1670389043243");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1670410643243");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20221128222455");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20221128222455");
user_pref("browser.startup.homepage_override.mstone", "107.0.1");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1670389080);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1670389041452");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "107.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "b19b63f9927d4123a3f5dc2d8af8b9bb");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221128222455");
user_pref("extensions.lastAppVersion", "107.0.1");
user_pref("extensions.lastPlatformVersion", "107.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"0e85265e-d354-4b08-9fec-683af2e1f4b2\",\"pictureinpicture@mozilla.org\":\"ac3bf16d-61bf-48e3-a2a7-0a7c722695e8\",\"screenshots@mozilla.org\":\"b83cd42a-3b95-4169-a18c-7a6dd10fc388\",\"webcompat-reporter@mozilla.org\":\"2791f53c-644d-45a9-832e-6e91f947cf88\",\"webcompat@mozilla.org\":\"bee720cf-d21e-41d8-a6cc-1b60569c0dd9\",\"default-theme@mozilla.org\":\"f0ed166e-2633-4c54-9335-3128266e1178\",\"addons-search-detection@mozilla.com\":\"abe50d64-8f64-47b2-9211-c8e79854cb1a\",\"google@search.mozilla.org\":\"36675aee-9413-4b91-a29f-7a7fecb1b5b4\",\"amazondotcom@search.mozilla.org\":\"dbe9eff4-aa8f-4334-9fe1-dcdcb513609a\",\"wikipedia@search.mozilla.org\":\"830f2a1a-4710-4d13-9ba4-8ecbd167f0db\",\"bing@search.mozilla.org\":\"dc3b3f44-e836-4a1b-a5ac-415b0d235ade\",\"ddg@search.mozilla.org\":\"29500c5c-c0ce-4a94-9e81-1504e2844924\",\"ebay@search.mozilla.org\":\"a4ce90bf-eeab-49f3-9d8f-f0cf024f6532\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1670389041);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.webrender", 4);
user_pref("gfx.blacklist.webrender.failureid", "FEATURE_FAILURE_DDX_INTEL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "1f6700a4-8929-4259-b144-900184747e8d");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1670389054);
user_pref("toolkit.telemetry.cachedClientID", "22a97cd2-cea4-40c0-85f2-9ce061f32665");
user_pref("toolkit.telemetry.previousBuildID", "20221128222455");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
